# Generated by Django 3.2.3 on 2021-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                default='default.png', upload_to='profile_pics'),
        ),
    ]
