# Generated by Django 3.2.3 on 2021-05-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='defualt-cover', upload_to='blog_covers'),
        ),
    ]
