# Generated by Django 3.2.3 on 2021-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='defualt-cover.jpg', upload_to='blog_covers'),
        ),
    ]
